"""create tables init

Revision ID: faf5c10ab46b
Revises: 
Create Date: 2024-05-01 03:23:20.978451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faf5c10ab46b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fingerprint_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fingerprint_type_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lattice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lattice_name', sa.String(), nullable=True),
    sa.Column('cif_filepath', sa.String(), nullable=True),
    sa.Column('mol_filepath', sa.String(), nullable=True),
    sa.Column('molecule_fingerprint', sa.String(), nullable=True),
    sa.Column('A', sa.Float(), nullable=True),
    sa.Column('B', sa.Float(), nullable=True),
    sa.Column('C', sa.Float(), nullable=True),
    sa.Column('dihedral_angle', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lattice_fingerprint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lattice_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint_type_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['fingerprint_type_id'], ['fingerprint_type.id'], name='fk_fingerprint_type_fingerprint_type_id'),
    sa.ForeignKeyConstraint(['lattice_id'], ['lattice.id'], name='fk_lattice_lattice_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lattice_fingerprint')
    op.drop_table('lattice')
    op.drop_table('fingerprint_type')
    # ### end Alembic commands ###
